# This file was generated by GoReleaser. DO NOT EDIT.
cask "distributed-metrics" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "f0534ee570b88886b6ea8eb8e825b04aa75ef4e554ae79a2abc79d6fd48a4630"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "205313900648bcebbd3276c95e96b6aed0cc402eb227e8c304e059c547f9ee51"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  on_linux do
    on_intel do
      sha256 "f122eed2eab3f57b98b292d1a62cf72791628cb7514a8d5998d899025cb2fa4d"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "4a661da327f653ee70931d5a2a4a3e5f2f0ec3f225deaa7394c37f0bb3862c58"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  name "distributed-metrics"
  desc "Monitoring tool backed by Bitping's distributed network"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "distributed-metrics"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/distributed-metrics"]
    end
  end

  # No zap stanza required

end
