# This file was generated by GoReleaser. DO NOT EDIT.
cask "distributed-metrics" do
  version "1.3.3"

  on_macos do
    on_intel do
      sha256 "2e3eebe442236a447a437bcfe65811c3acd81366d64945f1032e1aceafca9d44"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "19c77f89d280c63f4483ee59a606808968cc12c82856b79756420f9a5a465cbd"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  on_linux do
    on_intel do
      sha256 "392c2903b8f5574fd8dd4ef442590ce72fad5f6d29159ddc79b8f9dbf7d57cd2"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "790230ef14d0d33126811e90bd42970948fdee5e90d133b47e418da77ba3ff71"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  name "distributed-metrics"
  desc "Monitoring tool backed by Bitping's distributed network"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "distributed-metrics"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/distributed-metrics"]
    end
  end

  # No zap stanza required

end
