# This file was generated by GoReleaser. DO NOT EDIT.
cask "distributed-metrics" do
  version "1.4.1"

  on_macos do
    on_intel do
      sha256 "f4864bae2b22c8b3e9e8c398ebdc14cfd01fadd29726185b81872e95da498378"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "2a3a8ece049122d5a8c00d2f6ed2f737ee9d02a187e134bf22ae1e40ab793ed2"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  on_linux do
    on_intel do
      sha256 "bf87beee6010ea17b6877d0a9f714e43dbde03fb3d26e305dc0c58e3774473ea"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
    on_arm do
      sha256 "febc61a146579fe9b3aa1909bd326034240f10ffeb40965731891b0f31c1c41b"
      url "https://github.com/BitpingApp/distributed-metrics/releases/download/v#{version}/distributed-metrics-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/distributed-metrics"
    end
  end

  name "distributed-metrics"
  desc "Monitoring tool backed by Bitping's distributed network"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "distributed-metrics"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/distributed-metrics"]
    end
  end

  # No zap stanza required

end
