# This file was generated by GoReleaser. DO NOT EDIT.
cask "p2proxy" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "524b6360becfbddf09ba32b2e2bd75fde4ca69f8e93e22631589e987376f6afe"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "e1bd85b71ace3ef762e4d1ab3876344f4e16108fee176873c9bef6756aa12d54"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "7cf871513bee6f9bd03ed766d651c36b95e6515ce4a564c58401a25aacaca9ff"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "21c4b2b43c6bf381fac12cca163dd2f90526a1b2014fe0dc0de1c62e99eb0dd6"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  name "p2proxy"
  desc "Bitping P2P proxy daemon"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "p2proxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/p2proxy"]
    end
  end

  # No zap stanza required

end
