# This file was generated by GoReleaser. DO NOT EDIT.
cask "p2proxy" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "9218560eaf6134c7e80e9b3578f97e8f289751ac5a1e4a6ecd64d9ac6244ab0c"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "e8280186a4b792f5442f261e617e841012259ca60dc58f66981fc665f45476dc"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "394601dd698cde98132119a8d2c5c867e5f2dd9258f84f74f981143b1482d6dc"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "b4cdac840c19355768b8aea63f2b40aad3238f928315ca7c6fe7de2ab49f9e6f"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  name "p2proxy"
  desc "Bitping P2P proxy daemon"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "p2proxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/p2proxy"]
    end
  end

  # No zap stanza required

end
