# This file was generated by GoReleaser. DO NOT EDIT.
cask "p2proxy" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "40d714c1858d3d8b3e69aa701cbf4cf1ec8301ca23e3121890c03bc83c3d0a49"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "c17dc6fec7eaeed0f4d79189b7f479bf9ce08709854a3558d67f47a26f6154bf"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-darwin-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b957f2316cbb3e81471c0ef2f61b3df73ded29292c0a3aece7e348c482d3c98"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-amd64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
    on_arm do
      sha256 "33a6406391a26d809608f522cad0535bcdcc126407d1acfa41adaf226398a7ac"
      url "https://github.com/BitpingApp/p2proxy/releases/download/v#{version}/p2proxy-#{version}-linux-arm64.tar.xz",
        verified: "github.com/BitpingApp/p2proxy"
    end
  end

  name "p2proxy"
  desc "Bitping P2P proxy daemon"
  homepage "https://bitping.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "p2proxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/p2proxy"]
    end
  end

  # No zap stanza required

end
